### ISSUE TITLE
Steam Controller any time soon? 

### ISSUE THREAD

**Issue by twinpixxx** [v1993/evdevhook2#26]
Is there even a possibility of adding Steam Controller support? Or maybe some kind of ‘know-how’ to add and debug a new device, and I will make a PR.

**Comment by twinpixxx** [comment]
My workarounds: 
``` 
# Steam Controller
[28de:1142]
AccelMapping=x-y-z-
GyroMapping=x+y-z-
```

Then launch:
```
> G_RESOURCE_OVERLAYS='/org/v1993/evdevhook2/DeviceTypes.ini=/home/deck/custom/custom.ini' ./evdevhook2-v1.0.2-x86_64.AppImage
```

Output:
```
(3)(deck@steamdeck custom)$ G_RESOURCE_OVERLAYS='/org/v1993/evdevhook2/DeviceTypes.ini=/home/deck/custom/custom.ini' ./evdevhook2-v1.0.2-x86_64.AppImage
GLib-GIO-Message: 15:17:30.848: Adding GResources overlay '/org/v1993/evdevhook2/DeviceTypes.ini=/home/deck/custom/custom.ini'
GLib-GIO-Message: 15:17:30.850: Mapped file '/home/deck/custom/custom.ini' as a resource overlay
```

But still can not find my SC in devices list in Dolphin. Even like DSU or something. It's either weird or i'm doing something wrong.

**Comment by v1993** [comment]
Please check out https://github.com/kmicki/SteamDeckGyroDSU to see if it fits your needs. As far as I know, steam deck does not expose its motion data in a standard-compliant way, which IMO puts it outside of this project's scope. I'll gladly add support if Valve adds a standard-compliant driver (or already did so, I'm not watching them closely); look into other projects for the time being.

Finally - Dolphin in particular seems to have [native support](https://github.com/dolphin-emu/dolphin/tree/master/Source%2FCore%2FInputCommon%2FControllerInterface%2FSteamDeck) for steam deck inputs, which includes the gyroscope, so you shouldn't need a DSU server for it in the first place. Cheers!

**Comment by twinpixxx** [comment]
Thanks for your reply, but I think we kind of misunderstood each other. 
I was trying to make this work for *Steam Controller* not *Steam Deck *. 
@v1993

**Comment by v1993** [comment]
Ohh, my bad, I actually kind of forgot these exist. Whoops.

Sadly, I'm not familiar with these whatsoever and doubt Steam exposes the gyroscope via udev; the userland driver by enthusiasts (https://github.com/ynsta/steamcontroller) definitely does not currently implement it either. Your best bet is probably https://github.com/FrogTheFrog/steam-gyro-for-cemuhook - while it's not maintained anymore, appimages should still work in theory.
